apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: afnannaseem837/post:latest
        ports:
        - containerPort: 3127

---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  type: LoadBalancer
  ports:
  - port: 3127
    targetPort: 3127
  selector:
    app: post
